#!/bin/bash
if [ "$1" == "stress" ] 
then
echo Running stress tests...
python -m tests.stress_tests
else
echo Running integration tests...
python -m tests.curator_tests
python -m tests.client_tests
python -m tests.job_tests
fi
